### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by renkosteenbeek** [Aedes-datastandaarden/vera-openapi#15]
Wat schrijft Vera voor, of wat adviseert Vera betreffende breaking changes in de Vera standaard?

Concreet: 
- In release 4.0.18 zitten er breaking changes ("Link Betaalgegeven weggehaald bij Betalingsregeling").
- Dit zal in de toekomst ongetwijfeld vaker voorgaan komen. Dit moet niet tot productieverstoringen leiden.
- Vanuit Zig gaan we verbinden met diverse Vera systemen.
- Hoe weet ik welke versie gebruikt wordt? Hoe om te gaan met breaking changes?

Het lijkt mij niet handig dat dit per Vera implementatie onderling moet worden afgesproken. M'n verzoek is dat Vera hierin iets voorschrijft.

Alvast bedankt.

**Comment by PallettKngs** [comment]
Hoi @renkosteenbeek, 

Bedankt voor het aanmelden van uw issue en excuus voor de late terugkoppeling. Het is momenteel zo dat vanuit de werkgroep met regelmaat patches worden doorgevoerd t.b.v. de kwaliteit van de VERA standaard. Het kan dus inderdaad voorkomen dat zaken obsolete worden verklaard of dat andere changes optreden binnen de standaard. Technisch gezien is de change _niet_ breaking omdat in de techniek wordt voorgeschreven om de 'oude' (obsolete) verklaarde elementen niet te verwijderen maar te blijven ondersteunen. Op de Wiki zullen deze obsolete verklaarde elementen wel verdwijnen. Dat betekent in essentie dat de patches dus backwards compatible zijn. Wanneer dit niet het geval is zal dit duidelijk aangegeven worden vanuit de VERA werkgroep en de eerstvolgende keer zal naar verwachting bij versie 5.0 zijn. 

Uiteraard is het mogelijk om onderling afspraken te maken over de implementatie van de standaard en een specifieke versie daarvan zodat ondersteuning o.b.v. de oudere patches niet gebruikt hoeft te worden. Vooralsnog is dit het antwoord dat ik u momenteel kan geven. Ter informatie kan ik wel mededelen dat de werkgroep dit onderwerp (releases en de continuiteit daarvan) wel op de backlog heeft te staan om te bespreken. Mocht u toch nog vragen of opmerkingen hebben dan hoor ik het graag. 

mvg,

Thomas Pallett
