### ISSUE TITLE
Openen in SWAGGER-UI Editor

### ISSUE THREAD

**Issue by EdwigHuisman** [Aedes-datastandaarden/vera-openapi#17]
De openapi YAML bestanden zouden geopend moeten kunnen worden in een SWAGGER editor, zodat je de requests kunt bekijken en beoordelen. Dit is b.v. wel mogelijk voor 'Woonruimteverdeling', maar niet voor b.v. 'Vastgoed' of 'Financien'. Het laden van deze laatste definitie leidt tot een out-of-memory error van de Google Chrome browser die de swagger editor laadt.
Zonder deze mogelijkheid moeten de 'ruwe' yaml files met Notepad bekeken worden. 
Hierdoor is het zeer moeilijk om de standaard te beoordelen of er opmerkingen over te maken. Zeker nog vóór 6 april.

**Comment by peterjan-aedesdatastandaarden** [comment]
Hoi Edwig, 
Bedankt voor je reactie. De out-of-memory komt door circulaire verwijzingen, waarvan er nog een aantal aanwezig waren in de API's van de Informatiedomeinen. Deze gaan we corrigeren.
