### ISSUE TITLE
Energielabel en index gegevens uitwisselen

### ISSUE THREAD

**Issue by oalbers** [Aedes-datastandaarden/vera-openapi#18]
In de CORA is er een Business Object EP2 indicator uitgewerkt: https://cora.wikixl.nl/index.php/Id-ee9e8b06-abee-39ba-4c6f-14fb0753c558 
Nu zoek ik die ook in de VERA. Ik kom op dit moment namelijk alleen de Klasse Energieprestatie tegen in het informatiedomein Vastgoed. Deze lijkt nog op de NEN 7120 gebaseerd te zijn en niet op de NTA 8800. 
Klopt dat? En is het mogelijk om hier eventueel suggesties in te doen via een Fork en dan inschieten via een Pull request? Hebben jullie hier een guideline voor?

**Comment by PallettKngs** [comment]
Hoi @oalbers,

Je kan inderdaad via de klasse energieprestatie die op een eenheid is vastgelegd de kenmerken vastleggen die u wenst. De energieprestatie op de eenheid is een collectie. Indien wenselijk kunnen meerdere energieprestaties tegelijk vastgelegd worden als een oude en/of voorlopige prestatie relevant zijn. Middels de referentie data en de energieprestatie->soort kan je aangeven dat het om de 'EP2' variant gaat. Zie hiervoor de referentiedata van VERA, die is ook via GIT in te zien.

Op termijn heeft de werkgroep wel de intentie om ook via PR's suggesties te kunnen ontvangen, beoordelen en mogelijk doorvoeren maar daarvoor hebben wij momenteel nog geen werkproces. 

Heeft u hiermee voldoende antwoord op de vraag? Hoor graag. 

Met vriendelijke groet,

Thomas Pallett

**Comment by oalbers** [comment]
Zeker. En ik zie nu ook dat in de RC van 4.1 dit een stuk duidelijker te vinden is. Ik zat in versie 4.0 te kijken.
