### ISSUE TITLE
Inconsistente naamgeving (camelcasing) breekt code generatie op case insensitive OS

### ISSUE THREAD

**Issue by keesjan-nccw** [Aedes-datastandaarden/vera-openapi#20]
Bij het genereren van server stubs voor Java Spring m.b.v. de OpenAPI Generator op een Windows PC treedt er een naamconflict op. Het probleem ontstaat door een combinatie van een OS die niet case sensitive is (Windows), een generator die de entiteitnaam voor de attribuutnaam plakt en een inconsistente naamgeving (camelcasing) in het VERA schema.

Specifiek gaat het mis in informatiedomein Vastgoed met entiteit Eenheidadres (kleine 'a') en het attribuut Adres in entiteit Eenheid (wordt java class EenheidAdres). Dit resulteert in een bestand EenheidAdres.java (met hoofdletter 'A') waarin de class Eenheidadres (kleine 'a') gedefinieerd is. Met als gevolg een Java compilatie error:

> (...)/model/EenheidAdres.java:[30,8] class Eenheidadres is public, should be declared in a file named Eenheidadres.java

Wanneer in het Vastgoed schema entiteit Eenheidadres wordt hernoemd naar EenheidAdres werkt de code generator wel.

Aangezien andere *Adres entiteiten (BagAdres, BuitenlandsAdres, RelatieAdres) in VERA wél met een hoofdletter 'A' worden geschreven zou het naar mijn mening ook consistenter zijn om EenheidAdres i.p.v. Eenheidadres te gebruiken.

**Comment by peterjan-aedesdatastandaarden** [comment]
Beste Kees Jan,

Bedankt voor je reactie. We zijn het er mee eens dat de naamgeving nu niet consequent is. De richtlijn is dat we de Nederlandse taalregels volgen. Hierbij worden samengestelde zelfstandige naamwoorden als een nieuw zelfstandig naamwoord geschreven. Dus 'Fiets' + 'Stuur' wordt een nieuw zelfstandig naamwoord 'Fietsstuur'. 

Dit is in mijn beleving echter niet de kern van je probleem. 

Een code-generator moet twee verschillende klassen maken, namelijk een klasse van de zelfstandige entiteit "Eenheidadres" en voor Adres onder klasse Eenheid, waarbij de generator Eenheid en Adres aan elkaar plakt tot EenheidAdres. Dit zijn echter twee verschillende klassen en het is vreemd dat hierdoor een compilaitefout optreedt. Dit lijkt me dan geen correcte werking van de generator.

Ik heb even vergeleken met de generator van aspnetcore. Dan zie ik dat er twee verschillende klassen gemaakt worden:
  public partial class Eenheidadres : AdresBasis, IEquatable<Eenheidadres>
en
public partial class AllOfEenheidAdres : Adres, IEquatable<AllOfEenheidAdres>

In .NET wordt de laatste nog geprefixt met AllOf. Deze klassen conflicteren niet met elkaar.
Ik zie wel een ander probleem met de generatoren, namelijk dat ze (nog) niet goed overweg kunnen met oneOf constructies.

    Adres:
      oneOf:
        - $ref: '#/components/schemas/BuitenlandsAdres'
        - $ref: '#/components/schemas/Eenheidadres'
        - $ref: '#/components/schemas/Postadres'
        - $ref: '#/components/schemas/Adres-basis'

Een adres mag van een van deze types zijn, maar van klasse Adres wordt door generatoren vaak een lege klasse gegenereerd.

Hopelijk heb je hiermee voldoende antwoord?

**Comment by keesjan-nccw** [comment]
De generator 'spring' is niet te vergelijken met 'aspnetcore'.

Maar na verder graven in de documentatie en broncode van de OpenAPI Generator vond ik de oplossing door toevoegen van het volgende commandline argument:

--inline-schema-name-mappings Eenheid_adres=Eenheidsadres

Hiermee kun je de schema name mappings manipuleren. Bovenstaande Eenheid_adres is het attribuut adres in entiteit Eenheid. Daar maak ik met bovenstaande Eenheidsadres van. Hierdoor krijg ik twee klassen Eenheidsadres en Eenheidadres zonder naam conflict.
