### ISSUE TITLE
Bouwdelen en bouwkundige-elementen

### ISSUE THREAD

**Issue by tonniekrijger** [Aedes-datastandaarden/vera-openapi#24]
Wij zijn bezig met het ontwerp van een integratie voor conditiescores rondom binnenpakketten. Nu proberen we al onze API's te leiden via een VERA model. Hierbij zijn we een beetje zoekende naar de definities en verhoudingen van bouwdelen en bouwkundige-elementen. Zou je een binnenpakket 'badkamer' kunnen zien als bouwdeel, met als elementen: douchecabine en wastafel? Is dan een kraan of douchekop ook een element? Of is een douchecabine een bouwdeel, bestaande uit douchebak, scherm, kraan, afvoer.

We zijn benieuwd naar jullie idee hierbij.

Alvast bedankt.

**Comment by PallettKngs** [comment]
Goedemiddag @tonniekrijger,

Bedankt voor het delen van jouw vraag. We streven er naar om wekelijks op de vrijdag terugkoppeling te geven op aangemelde issues. Naar verwachting zal je vrijdag antwoord krijgen op je vraag. 

Fijne dag en vriendelijke groet,

Thomas Pallett

**Comment by EwoutAtAedes** [comment]
Beste @tonniekrijger, 

Conditiescores worden normaliter gedefinieerd op de schil van de eenheid/cluster zoals dak, kozijnen, etc. en niet zozeer de binnenkant van een eenheid. Het is uiteraard wel mogelijk om dat te doen maar daarmee wordt het conditiemeten vaak een dure aangelegenheid (omdat je elke woning apart moet gaan opnemen). Conditiemeting wordt in VERA vastgelegd op Cluster-niveau als berekende (gemiddelde) score vlg. de NEN-norm. De relatie van een Cluster met Bouwdelen en BouwkundigeElementen loopt via Eenheid of CollectiefObject naar Bouwdeel en van Bouwdeel naar BouwkundigElement. De 'detailscores' (de onderlegger voor de berekende score) is **niet gemodelleerd in VERA** en dus ook niet via een VERA-API uit te wisselen. Deze details liggen vast in het MJOB-systeem.

Het verschil tussen Bouwdeel en BouwkundigElement is dat een Bouwdeel kan bestaan uit meerdere BouwkundigeElementen (1 op n-relatie). Een bouwdeel kan een lift zijn waarbij de bouwkundige elementen de deur, motor, etc. is. Het niveau voor de detailscores kun je zelf bepalen maar het niveau van een BouwkundigElement 'voelt' wel het beste. 

Met vriendelijke groet,
Ewout van der Wielen

**Comment by tonniekrijger** [comment]
Bedankt voor de toelichting. Dan zullen we hier en daar nog velden toe moeten voegen om dit te kunnen realiseren.
