### ISSUE TITLE
Vertrekdatum staat dubbel bij de huidige huurder

### ISSUE THREAD

**Issue by pfheek** [Aedes-datastandaarden/vera-openapi#25]
https://github.com/Aedes-datastandaarden/vera-openapi/blob/9e5ad27f6fe0a58c69d80412778eff6b32344634/Ketenprocessen/WRV.yaml#L7438C8-L7442C27

**Comment by EwoutAtAedes** [comment]
Zie andere opmerking; Vertrekdatum is OBSOLETE en vertrekdatum is nieuw toegevoegd ivm lowerCamelCase-conventie
