### ISSUE TITLE
Vertrekdatum zit er dubbel in met en zonder hoofdletter V

### ISSUE THREAD

**Issue by pfheek** [Aedes-datastandaarden/vera-openapi#26]
https://github.com/Aedes-datastandaarden/vera-openapi/blob/9e5ad27f6fe0a58c69d80412778eff6b32344634/Ketenprocessen/WRV.yaml#L7438C9-L7446C65

**Comment by EwoutAtAedes** [comment]
Het attribuut "vertrekdatum" was initieel toegevoegd met een hoofdletter "Vertrekdatum" terwijl de naamconventie op basis van lowerCamelCase is. Daarom hebben we Vertrekdatum obsolete verklaard en is het attribuut "vertrekdatum" toegevoegd.
