### ISSUE TITLE
Bewakingsstatus zit al in Overeenkomst-Basis. Kan hier dus weg

### ISSUE THREAD

**Issue by pfheek** [Aedes-datastandaarden/vera-openapi#27]
https://github.com/Aedes-datastandaarden/vera-openapi/blob/9e5ad27f6fe0a58c69d80412778eff6b32344634/Ketenprocessen/BOG.yaml#L900C1-L903C63

**Comment by EwoutAtAedes** [comment]
Hoi @pfheek, bedankt voor het melden! Dit issue was al bekend en ook eerder opgelost. Graag de laatste versie van de BOG gebruiken.

**Comment by pfheek** [comment]
Het zit in de laatste versie ook niet goed

**Comment by EwoutAtAedes** [comment]
Even gecontroleerd en je hebt gelijk, de aanpassing is al wel in de brongegevens doorgevoerd maar nog niet in een release van de YAML opgenomen. Was in de war geraakt doordat de Swagger-editor het probleem van dubbele attributen blijkbaar zelf oplost in de weergave...
