### ISSUE TITLE
 maximunleeftijd =>  maximumleeftijd

### ISSUE THREAD

**Issue by pfheek** [Aedes-datastandaarden/vera-openapi#28]
https://github.com/Aedes-datastandaarden/vera-openapi/blob/9e5ad27f6fe0a58c69d80412778eff6b32344634/Ketenprocessen/WRV.yaml#L4708C8-L4708C24

**Comment by MarcelVanDenBos** [comment]
Dank voor je melding. We hebben een nieuw attribuut met de juiste spelling toegevoegd en het oude obsolete verklaard. We zullen deze wijziging in patch 3 opleveren.
