### ISSUE TITLE
Boekingen - alleen openstaande

### ISSUE THREAD

**Issue by renkosteenbeek** [Aedes-datastandaarden/vera-openapi#30]
In de Vera spec staat het volgende:

"Opvragen Boeking: Het is gewenst om bij klantcontacten met een relatie te weten wat de debiteurenpositie is en welke posten nog open staan. "
Zie https://cora.wikixl.nl/index.php/Id-30853da3-336e-6549-2f19-38f0690e77f5.

Deze tekst kan dus worden gelezen als: "Alleen de openstaande boekingen worden weergegeven". Dit is géén goede keuze. Via de Vera APIs zou het mogelijk moeten zijn om **alle** boekingen op te halen. Als iemand alleen de openstaande wilt zien, dan kan er prima worden gefiltert worden op status van een boeking.

Kan dit worden aangepast? Mijn inziens is het nu foutief. Alvast bedankt.

**Comment by RonaldTimmerman** [comment]
Dag Ren, allereerst dank voor je vraag. Ik heb er even naar gekeken en volgens mij kun je de verwijzing naar 'openstaande posten' lezen als een voorbeeld/context. 

Wanneer je kijkt naar de tekst 'Hiervoor is het gewenst om de boekingen en afletteringen op te vragen zodat bepaald kan worden welke posten nog (deels) betaald moeten worden.', dan kun je daaruit lezen dat je alle boekingen kunt ophalen om op basis daarvan de eventuele openstaande posten te bepalen.

In dat kader hebben we recent een attribuut 'Afletterstatus' toegevoegd, waarmee het uitfilteren van openstaande posten makkelijker zou moeten zijn geworden.

Ik hoop dat je vraag hiermee is beantwoord en uiteraard horen we het graag als er nog iets onduidelijk is.

Vriendelijke groeten,

Ronald Timmerman
VERA Architectuurteam

**Comment by renkosteenbeek** [comment]
Helder, Ronald. Dank voor je toelichting!
