### ISSUE TITLE
Referentiedata & landen niet duidelijk

### ISSUE THREAD

**Issue by renkosteenbeek** [Aedes-datastandaarden/vera-openapi#31]
https://cora.wikixl.nl/index.php/Referentiedata:LAND

Dit is niet duidelijk. Waar staat dit tabblad?

**Comment by EwoutAtAedes** [comment]
Hoi Renko, de referentiedata van LAND (en ook NATIONALITEIT) worden niet geleverd door VERA maar we verwijzen daarbij naar de nationale/internationale standaarden die er zijn. Voor landen is dat de ISO-3166 standaard (https://www.iso.org/iso-3166-country-codes.html) waarbij we de Alpha-2 codering (2 letterige codering). We zullen in de documentatie hier even naar verwijzen en de huidige tekst in de referentiedata aanpassen.
