### ISSUE TITLE
Klasse 'Relatierol' mist het 'rolRelatie' attribuut

### ISSUE THREAD

**Issue by RobertBijl** [Aedes-datastandaarden/vera-openapi#32]
Bij het upgraden naar de laatste versie viel het ons op dat het attribuut 'rolRelatie' niet langer bestaat op de 'Relatierol' klasse. Deze is nog wel in de documentatie terug te vinden: [4.1 patches](https://cora.wikixl.nl/index.php/Id-bf7d96dd-3ebd-98f8-cd7d-28114b106210).

4.0.19 is de laatste versie waar ik dit attribuut nog aantref. Zouden jullie dit kunnen ophelderen?

Alvast bedankt!

**Comment by EwoutAtAedes** [comment]
Beste Robert, het attribuut rolRelatie is toegevoegd in de laatste patch (4.1.3). In de releasenotes was dit echter niet opgenomen. Alsnog toegevoegd. Dank voor het melden!
