### ISSUE TITLE
Toegankelijkheidslabel kunnen er meer zijn.

### ISSUE THREAD

**Issue by pfheek** [Aedes-datastandaarden/vera-openapi#33]
Volgens mij moet Toegankelijkheidslabel Toegankelijkheidslabels en dus een array zijn. 

https://github.com/Aedes-datastandaarden/vera-openapi/blob/79751b4098c9d7675c7f92d9defc695abbc54340/Ketenprocessen/WRV.yaml#L4646C1-L4650C2

**Comment by MartijnVermeulenVERA** [comment]
Hallo Peter-Frans,

Binnen de toegankelijkheidslabels wordt een hiërarchie verondersteld: een Extra ruime rolstolwoning (RUI) is per definitie ook een Rolstoelwoning (ROL) én een Rollatorwoning (ROA) én een Gelijkvloerse woning (GEL). Met andere woorden: het is voldoende om de 'hoogst mogelijke' toegankelijkheid vast te leggen. Eén label is om die reden voldoende.

**Comment by pfheek** [comment]
Dit is nieuw in vera4? In vera3.* had je wel meerdere labels namelijk.

**Comment by MartijnVermeulenVERA** [comment]
Op de Wiki kan ik nog terug naar VERA 3.2.1, maar ook daar is sprak van één attribuut "Toegankelijkheidslabel"; het was geen collectie. In het algemeen geldt overigens dat er maar één referentiedata waarde gebruikt kan worden. Ook functioneel (zie de omschrijvingen van de verschillende toegankelijkheidslabels) is er geen noodzaak om meer dan één label te kiezen.
Hebben we het misschien over verschillende zaken? Kan jij nog ergens terughalen wat je in VERA 3.x hebt gezien en nu mist?

**Comment by pfheek** [comment]
Hmm. Ik zie in mijn logging toegankelijkheidslabels binnen komen maar in de wsdl inderdaad toegankelijkheidslabel staan. Begrijp zo snel niet waar het vandaan komt dat het anders is. 
Sluit het issue maar.
