### ISSUE TITLE
Onderhoudsverzoeken zit al in overeenkomstbasis. Weet niet waar het echt thuishoort, maar in beide lijkt me niet de bedoeling

### ISSUE THREAD

**Issue by pfheek** [Aedes-datastandaarden/vera-openapi#34]
https://github.com/Aedes-datastandaarden/vera-openapi/blob/c0d3916795ad5e9bfbc451a2f335f6cc91a3b8f5/Ketenprocessen/BOG.yaml#L955

**Comment by EwoutAtAedes** [comment]
Beste Peter Frans, je hebt helemaal gelijk. We gaan dit aanpassen!

**Comment by EwoutAtAedes** [comment]
onderhoudsverzoeken is een collectie binnen Huurovereenkomst. In BOG/Overeenkomsten stond dit attribuut per abuis ook. Dit zal in VERA 4.1.4 uitgeleverd worden
