### ISSUE TITLE
Opzegtermijn zit zowel in overeenkomst-basis als in overeenkomst-huurovereenkomst. Lijkt me niet de bedoeling.

### ISSUE THREAD

**Issue by pfheek** [Aedes-datastandaarden/vera-openapi#36]
https://github.com/Aedes-datastandaarden/vera-openapi/blob/c0d3916795ad5e9bfbc451a2f335f6cc91a3b8f5/Ketenprocessen/BOG.yaml#L960

**Comment by peterjanvandeput** [comment]
Dat is inderdaad niet correct. We gaan dit aanpassen.

**Comment by EwoutAtAedes** [comment]
Is opgelost in VERA 4.1.4
