### ISSUE TITLE
Uitbreiding Referentiedata SIGNALERINGDETAILSOORT

### ISSUE THREAD

**Issue by renkosteenbeek** [Aedes-datastandaarden/vera-openapi#37]
Naast de bestaande signaleringdetailsoorten, zoals Bewindvoerder of Deurwaarder, zou ik graag de soort "Begeleider" toegevoegd willen zien. Hiermee is het mogelijk dat een huurder een begeleider heeft, wat vaak relevant is voor medewerkers om te weten.

Te gebruiken in: https://cora.wikixl.nl/index.php/Id-5eb74102-4eba-8e30-2c68-5824a608881e

**Comment by EwoutAtAedes** [comment]
Kun je aangeven wat je precies bedoeld met "begeleider"? We kunnen wellicht een ambulante begeleider toevoegen aan de relatierolsoorten zodat je aan een relatie een andere relatie kan koppelen met deze specifieke rol. In hoeverre je dan nog een signalering nodig hebt is dan wel de vraag, je kunt dit dan opvragen bij de specifieke relatie.

**Comment by renkosteenbeek** [comment]
Inderdaad ambulant begeleider. 

> In hoeverre je dan nog een signalering nodig hebt is dan wel de vraag, je kunt dit dan opvragen bij de specifieke relatie.
Dat geldt toch ook voor deurwaarder en bewindvoerder? Waarom bestaat dit als signalerings detailsoort?

**Comment by EwoutAtAedes** [comment]
Bij signaleringen kun je met 1 call alle signaleringen ophalen, anders zou je voor elke signalering een aparte call moeten doen.

**Comment by EwoutAtAedes** [comment]
Ik zeg niet dat het moet en ook niet dat een signalering niet mogelijk is :) Signalering Ambulante begeleider en relatierolsoort Ambulante begeleider is idd de meest consequente oplossing:  via Signaleringen weet je of een relatie een ambulante begeleider heeft, of een bewindvoerder, of een lopende deurwaarderszaak. Aan de hand van andere resources kan specifieke informatie opgehaald worden, zoals de deurwaarderszaakgegevens via INC/ExterneIncassos. RFC is dus: toevoegen van de relatierolsoort "Ambulante begeleider" en de signaleringdetailsoort "Ambulante begeleiding" met een signaleringsoort. Heb je een voorstel voor signaleringsoort?

**Comment by renkosteenbeek** [comment]
Ja, we zijn het met elkaar eens.

Signaleringsoort: Lastig, ook Bewindvoerder en Deurwaarder kan ik lastig aan een bestaande signaleringsoort koppelen. Wat denk je van "Deskundige begeleiding"?

**Comment by EwoutAtAedes** [comment]
Wordt opgenomen in de volgende patch van referentiedata:
- Code: AMB
- Naam: Ambulante begeleiding
- Omschrijving: De relatie krijgt in de eigen omgeving externe hulp om zo zelfstandig mogelijk te blijven functioneren.
