### ISSUE TITLE
Deurwaarderszaak, Bewindvoerder & signaleringen: contactgegevens deurwaarder

### ISSUE THREAD

**Issue by renkosteenbeek** [Aedes-datastandaarden/vera-openapi#38]
Ik wil de mogelijkheid hebben om zoiets als een deurwaarderszaak of bewindvoerder als 'signalering' door te geven. De huidige Vera koppelingen faciliteren hierin, gezien de detailSoort met de waarden Bewindvoerder en Deurwaarder worden ondersteund.

In deze gevallen is het heel voor de hand liggend om aan te geven wié de deurwaarder of bewindvoerder is. In de huidige structuur zou dit passen in het element "relatie". Hierover staat in de Vera spec: "De relatie behorend bij de signalering.". Maar eigenlijk is het logisch dat dit de relatie betreft die een bewindvoerder of deurwaarder heeft (de huurder), helemaal omdat dit veld ook wordt gebruikt om signaleringen op te zoeken.

M'n vraag is dus: Wat is binnen de huidige structuur de juiste plaats om de deurwaarder of bewindvoerder te koppelen aan een signalering? 

https://cora.wikixl.nl/index.php/Id-5eb74102-4eba-8e30-2c68-5824a608881e

**Comment by EwoutAtAedes** [comment]
Hoi Renko, de signalering bevat geen link naar de deurwaarder en is ook alleen bedoeld als signalering bij een specifieke relatie. Als je de signalering "Deurwaarderszaak" krijgt kun je de zaakgegevens ophalen met de resource ExterneIncassos in het ketenproces Incasso. Bij signalering bewindvoerder zou je de informatie van de bewindvoerder moeten kunnen ophalen via de BRG/Relaties resource met relatierol met rolsoort = 'BWI'

**Comment by renkosteenbeek** [comment]
Ja, begrijp ik. Ok 👍
