### ISSUE TITLE
Uitbreiding Referentiedata RELATIEROLSOORT

### ISSUE THREAD

**Issue by renkosteenbeek** [Aedes-datastandaarden/vera-openapi#39]
Na navolging van deze:
https://github.com/Aedes-datastandaarden/vera-openapi/issues/37

Graag zou ik de rol Ambulant Begeleider willen laten toevoegen.

**Comment by EwoutAtAedes** [comment]
Wordt toegevoegd in de volgende patch van de referentiedata
- code: AMB
- naam: Ambulante begeleider
- omschrijving: De ambulant begeleider helpt mensen om regie te voeren over hun eigen leven en zo veel mogelijk zelfstandig te functioneren
