### ISSUE TITLE
Uitbreiding Referentiedata RELATIEROLSOORT

### ISSUE THREAD

**Issue by DanielFortuyn** [Aedes-datastandaarden/vera-openapi#40]
In navolging van eerdere verzoeken bij deze ook het verzoek om de relatierolsoort regiokantoor toe te voegen

**Comment by MarcelVanDenBos** [comment]
Goedemorgen, we komen hier toch nog even op terug. Wat bedoel je met een regiokantoor?

**Comment by DanielFortuyn** [comment]
Sommige vastgoedorganisaties hebben verschillende regiokantoren. We zouden deze graag als relatierolsoort opnemen.

**Comment by MarcelVanDenBos** [comment]
Goedemorgen Daniel. We denken dat wat jij bedoeld gaat over verschillende vestigingen van corporaties. Corporaties die in meerdere regio's actief zijn hebben daar doorgaans een vestiging per regio. In onze modellen noemen we dit dus vestiging. Vestiging is van het type Referentiedata. Je kunt dus een code en een Naam opgeven. VERA schrijft voor dit veld geen waarden voor. Op diverse klassen is dit attribuut beschikbaar: https://www.coraveraonline.nl/index.php/ReferentiedataSoort:VESTIGING
