### ISSUE TITLE
Informatiedomein Vastgoed: Ruimte - toevoegen verwarmd (Boolean)

### ISSUE THREAD

**Issue by oalbers** [Aedes-datastandaarden/vera-openapi#41]
Om de woningwaardering te kunnen berekenen wil je weten of een Ruimte (Vertrek) verwarmd is. Dit kenmerk is nu niet aanwezig. Kan dit toegevoegd worden?

**Comment by peterjan-aedesdatastandaarden** [comment]
Bedankt voor deze issue. Het klopt dat je momenteel niet op een vertrek kan aangeven of het verwarmd is en zo ja welke type verwarming. In VERA is een vertrek een Ruimte van het soort 'vertrek'. Entiteit Ruimte zullen we waarschijnlijk dan uitbreiden met een attribuut om de klimaatbeheersing te specificeren. We zullen dan tevens aan de huidige referentiedata EENHEIDKLIMAATBEHEERSING de code  "onverwarmd" toevoegen
