### ISSUE TITLE
Dubbele regel Loggia

### ISSUE THREAD

**Issue by Datatoppers** [Aedes-datastandaarden/vera-openapi#42]
Voor een dataplatform gebruiken wij het volgende eindpoint om data uit VERA te ontsluiten:
https://vera-service.azurewebsites.net/api/referentiedata

Sinds 9 maart krijg ik echter op dit endpoint 2 regels binnen voor Loggia op informatiedomein vastgoed, waarbij 1 wél een description heeft en de ander niet. Dit verstoort onze ETL-processen:

soort            : RUIMTEDETAILSOORT
code             : LOG
naam             : Loggia
omschrijving     :
parent           : @{soort=RUIMTESOORT; code=BTR}
begindatum       : 19-1-2024
einddatum        :
sortering        :
informatieDomein : Vastgoed

soort            : RUIMTEDETAILSOORT
code             : LOG
naam             : Loggia
omschrijving     : Buitenruimte: een inpandig balkon.
parent           : @{soort=RUIMTESOORT; code=BTR}
begindatum       : 12-01-2024
einddatum        :
sortering        :
informatieDomein : Vastgoed

**Comment by peterjan-aedesdatastandaarden** [comment]
Bedankt voor je melding. We hebben de dubbele regel verwijderd en zullen vandaag een patch publiceren.
