### ISSUE TITLE
Dossier koppeling Vastgoedobject

### ISSUE THREAD

**Issue by bastiaanrodenburg** [Aedes-datastandaarden/vera-openapi#43]
Ik ben bezig met Asbest en VERA. Ik wil het gaan vastleggen als informatieobject en dossier bij een vastgoedobject. Met name omdat we alleen rapporten hebben waar de details in staan en we de informatie niet hebben in een format om het op bouwdeel of bouwkundigelement vast te leggen. 
Dit issue gaat hierover: In de tekst van Dossier staat: _ze horen bij een voor de woningcorporatie relevant onderwerp bijvoorbeeld een relatie, vastgoedobject, project of thema.  Maar in de implementatie zie ik geen relatie met iets van vastgoed. Nu is er ook niet 1 gemeenschappelijk vastgoedobject waar je aan kan linken. Maar ik zou het vast willen leggen op een pand of een verblijfsobject.

**Comment by EwoutAtAedes** [comment]
Beste Bastiaan, je kunt via de entiteit Zaakobject een relatie leggen tussen het informatieobject met een andere entiteit binnen VERA. Door het gebruik van de referentiedata ZAAKOBJECTSOORT kun je specificeren om welke entiteit het gaat. Rondom vastgoed hebben we nu Eenheid, Cluster en CollectiefObject beschikbaar maar daar kunnen we ook Pand aan toevoegen. Wil je aangeven welk entiteiten een relatie vanuit het informatieobject moet krijgen?

PS. daarnaast is aan elke entiteit in VERA standaard een relatie te leggen met informatieobjecten, zie hiervoor ook de Swagger-documentatie.

**Comment by bastiaanrodenburg** [comment]
Via Zaakobject zie ik ook geen relatie met andere entiteiten. Ik zie wel ZAAKOBJECTSOORT, maar waar vul ik dan de id van bijv. de eenheid in? Ik verwacht van een koppelobject dat het gekoppelde object er ook in zit. Bijvoorbeeld zo:

```
Dossier: {
   "omschrijving" : "mijn asbestdossier",
   "zaakobjecten": [
      {
          "soort": {
              "code": "EEN"
           }
          "object": {
               "id": "eenheidid",
               "adres": {
               }
          }
      }
   ]
}
```

Een Asbest-dossier zou gekoppeld moeten kunnen worden aan een Cluster, een Eenheid een Ruimte. Of nog beter: de vastgoed-varianten hiervan. Is dat Pand, Verblijfsobject en Bouwdeel? Ik begrijp dat stuk gaat wijzigen, dus ik laat dat aan jullie.

**Comment by peterjan-aedesdatastandaarden** [comment]
Beste Bastiaan,
Het is mogelijk verwarrend. Maar de Id van het Zaakobject is het id van het object waar naar verwezen wordt. Dus als je objecten toevoegt neem je daarvan alleen de soort en de kerngegevens op. Dus bijvoorbeeld voor Eenheid en Cluster, zou het er zo uit moeten zien:

Dossier: {
   "omschrijving" : "mijn asbestdossier",
   "zaakobjecten": [
      {
         "id": "eenheidid"
          "soort": {
              "code": "EEN"
           }
      },
      {
         "id": "clusterid"
          "soort": {
              "code": "CLU"
           }
      }   ]
}

**Comment by bastiaanrodenburg** [comment]
Ok, ja inderdaad verwarrend inderdaad. Ik zou dat interpreteren als het id
van het koppelobject. Maar ik kan me ook goed voorstellen dat je nog wel
eens een dossier of zaak wilt communiceren incl. de betrokken objecten. Dus
met niet alleen het id maar ook met wat gegevens erbij. Maar voor nu is het
duidelijk. Bedankt.

Op ma 8 apr 2024 om 15:03 schreef PeterJan van de Put <
***@***.***>:
