### ISSUE TITLE
Bouwjaar op bouwkundig element

### ISSUE THREAD

**Issue by bastiaanrodenburg** [Aedes-datastandaarden/vera-openapi#45]
Ik wil van een bouwkundig element het bouwjaar vast kunnen leggen. Bijvoorbeeld van belang bij een CV-ketel, lift etc. Het bouwjaar geeft specialisten veel informatie over bijvoorbeeld de kwaliteit, het type, de bouwkwaliteit, de regelgeving die destijds golden.

**Comment by EwoutAtAedes** [comment]
Beste Bastiaan, binnen Bouwkundigelement heb je de mogelijkheid om een begindatum op te geven. Dat is niet helemaal hetzelfde als bouwjaar maar je kunt het er wel voor gebruiken. Deze vraag (bouwjaar vastleggen bij bouwkundig element) nemen we mee in de doorontwikkeling van het vastgoed informatie model samen met CORA en de Aedes ILS expertgroep.
