### ISSUE TITLE
Relatie tussen ruimte en bouwkundig element

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-openapi#46]
Voor sommige stelselgroepen binnen het woningwaardering stelsel moeten we weten of een ruimte een bepaald bouwkundig element heeft. Zoals bijvoorbeeld een zolder met een vlizotrap, of een keuken met een aanrecht.

In de VERA standaard is er wel een relatie tussen bouwkundige elementen en bouwdelen, maar niet tussen ruimtes en bouwkundige elementen of tussen ruimtes en bouwdelen, waardoor niet te herleiden is bij welke ruimte een bouwkundig element hoort.

Binnen de Woonstad datamodellen hebben wij hiervoor het attribuut bouwkundigeElementen aan het model voor ruimtes toegevoegd. Zou er ook een dergelijke relatie in de VERA modellen toegevoegd kunnen worden?

**Comment by EwoutAtAedes** [comment]
Beste Ben, zie hiervoor onze reactie bij issue #46

**Comment by benverhees** [comment]
Ik neem aan dat je #47 bedoelt, dank je voor je reactie!

**Comment by MarcelVanDenBos** [comment]
We voegen deze toe aan VERA 4.1.6
