### ISSUE TITLE
Relatie tussen ruimtes

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-openapi#47]
In het beleidsboek woningwaardering zelfstandige woonruimte onder 4.2.2 punt 1 staat het volgende ten aanzien van de waardering van de oppervlakte van vaste kasten:

> “Alle tot de woning behorende losse en vaste kasten” leest de Huurcommissie als: “alle tot de vertrekken behorende kasten”. De plaats van de deur van de kast bepaalt bij welk vertrek de kast behoort. Dus een kast die in een vertrek uitkomt wordt, ongeacht de afmeting, bij dat vertrek geteld. Dat geldt ook voor het waarderen van een kastenwand tussen twee vertrekken.
> 
> - Van vaste kasten (kleiner dan 2m²) wordt de netto oppervlakte bepaald en bij de oppervlakte van het betreffende vertrek opgeteld;
> - Een kast, (kleiner dan 2m²) waarvan de deur uitkomt op een verkeersruimte, wordt niet gewaardeerd;

Om te bepalen in welke ruimte een bergruimte zoals een vaste kast uitkomt, zou er een relatie tussen ruimten onderling moeten bestaan. Kan deze relatie toegevoegd worden aan de VERA modellen?

**Comment by EwoutAtAedes** [comment]
Beste Ben, 
de vaste kast is een bouwkundig element en kun je specificeren in de gelijknamige entiteit. Vanaf de laatste versie (4.1.4) zijn attributen opgenomen voor oa. lengte en diepte en tevens een uitbreiding van de referentiedata voor BOUWKUNDIGELEMENTDETAILSOORT vlg. de Aedes ILS. Het is goed om dit hier vast te leggen.
De koppeling tussen ruimte en bouwkundig element is op dit moment nog niet 1-op-1 te koppelen (dit loopt nu oa via Eenheid). Binnen Aedes datastandaarden en CORA zijn we bezig met de doorontwikkeling van het hele vastgoed informatie model.

**Comment by benverhees** [comment]
@EwoutAtAedes het gaat hier ook om inbouwkasten, en dat is volgens de Aedes ILS het ruimtetype kast, en niet een bouwkundig element.

**Comment by RomyMans** [comment]
Hi Ben,
Het vastleggen van relaties tussen ruimtes en relaties tussen een ruimte en bouwkundig element (#46 ) hebben we genoteerd als wens voor doorontwikkeling van de ILS. Zoals Ewout ook al noemde zijn we bij Aedes, met VERA en CORA breder bezig met een vastgoed informatie model. Waar deze relaties dus precies een plek krijgen is nog een de vraag, wanneer dit concreter begint te worden zal ik hier een update geven.

Wat betreft het toevoegen van inbouwkast als ruimte, zie mijn reactie bij issue [#91](https://github.com/Aedes-datastandaarden/vera-referentiedata/issues/91)

**Comment by MarcelVanDenBos** [comment]
De relatie tussen Ruimte en Bouwkundige elementen nemen we op in VERA 4.1.6

**Comment by benverhees** [comment]
@MarcelVanDenBos de wens hier omvat juist een relatie tussen ruimtes onderling; zoals bijvoorbeeld een kast/berging die als ruimte gedefinieerd is, waarvan de deur in een woon- of slaapkamer uitkomt.
