### ISSUE TITLE
Orientatie of ligging op BouwkundigElement

### ISSUE THREAD

**Issue by bastiaanrodenburg** [Aedes-datastandaarden/vera-openapi#48]
Ik wil de oriëntatie of ligging van een bouwkundig element vast kunnen leggen. Dus noord/oost/zuid/west en de vier richtingen daartussen. Ook horizontaal is een geldige waarde. Ligging kan gebruikt worden voor bijvoorbeeld daken, zonnepanelen, zonwering en gevels.
Er is wel zo'n mogelijkheid op Ruimte.

**Comment by EwoutAtAedes** [comment]
Beste Bastiaan, kun je aangeven met welk doel je deze oriëntatie wil vastleggen? En welke eventueel andere gegevens wil je daarbij vastleggen? Gaat het bijvoorbeeld ook om 3D eigenschappen, zoals bijvoorbeeld de hellingshoek van de zonnepanelen? Wij kunnen het daarna intern bespreken met het Aedes ILS expertteam.

**Comment by bastiaanrodenburg** [comment]
De oriëntatie geeft energiespecialisten snelle eerste info over de effectiviteit van bijv. zonnepanelen of zonwering. Ook geeft het info over de onderhoudsbehoefte. Andere 3D eigenschappen van een bouwkundig element hebben wij in VERA-formaat niet direct nodig. Dat is te gedetailleerd naar onze mening. Maar een hellingshoek kan ik me wel voorstellen als attribuut. Kan ook van toepassing zijn bij bijvoorbeeld schuine daken (wat ook een bouwkundig element is).

**Comment by RomyMans** [comment]
Hi Bastiaan! Ik reageer ook alvast namens de Aedes ILS groep. Wij hebben de intentie om oriëntatie en ligging van een bouwkundig element als optioneel mee te nemen in de volgende versie (3.0). We zullen daar invulling aan geven op basis van het Woonstad model (met hulp van jouw collega Bernd)

**Comment by RomyMans** [comment]
Aanvulling: Orientatie is opgenomen in de ILS-woco 3.0a, als volgt: 

Orientatie (parameter met enumeraties:)
- N
- NO
- O
- ZO
- Z
- ZW
- W
- NW
