### ISSUE TITLE
Dode link in README

### ISSUE THREAD

**Issue by renkosteenbeek** [Aedes-datastandaarden/vera-openapi#49]
Zie
https://github.com/Aedes-datastandaarden/vera-openapi?tab=readme-ov-file#implementatiestandaarden-vera

Er wordt verwezen naar deze pagina, deze bestaat niet meer:
https://www.coraveraonline.nl/index.php/Identificatie_objecten_in_VERA

Graag oplossen 👍

**Comment by EwoutAtAedes** [comment]
thanks, aangepast
