### ISSUE TITLE
Invalide `format: any` specificatie voor strings

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-openapi#52]
De VERA OpenApi specificaties gebruiken `any` als format voor `string`. Bijvoorbeeld: https://github.com/Aedes-datastandaarden/vera-openapi/blob/1c69ba8e3565b5528491859aeae6dd0e144e1922/Ketenprocessen/BVG.yaml#L1480-L1482
`any` is geen bestaand format binnen de OpenApi standaard: https://spec.openapis.org/registry/format/. Indien er geen specifiek format is voor een string instance, dient `format` weggelaten te worden.

**Comment by peterjan-aedesdatastandaarden** [comment]
Beste Ben, Bedankt hiervoor, ik het aangepast. In onze volgende release zal format niet meer voorkomen bij vrije waarden.
