### ISSUE TITLE
Zelfverwijzende relatie mist in Referentiedata model

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-openapi#53]
De VERA referentiedata kent een zelfverwijzende relatie, in de CSV gespecificeerd als Parent. Het referentiedata model mist echter een attribuut voor deze relatie. Dit is nodig om bijvoorbeeld van een `Eenheidklimaatbeheersing` de parent `Eenheidklimaatbeheersingsoort` te bereiken. Kan dit toegevoegd worden?
https://github.com/Aedes-datastandaarden/vera-openapi/blob/1c69ba8e3565b5528491859aeae6dd0e144e1922/Ketenprocessen/BVG.yaml#L1473-L1483

**Comment by MarcelVanDenBos** [comment]
Normaliter zit het attribuut van de parent ook op het object in zit. Dat gaan we ook hier zo oplossen. Dus dan hoeft de parent zelf niet beschikbaar te zijn als attribuut.
