### ISSUE TITLE
Referentiedata `Eenheidklimaatbeheersingsoort` wordt nog niet gebruikt in de modellen

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-openapi#54]
Recent is de referentiedata voor EENHEIDKLIMAATBEHEERSINGSOORT toegevoegd, echter deze wordt nog nergens gebruikt in de modellen.
Is het de bedoeling dat dit nog toegevoegd wordt, of dient dit via de parent op EENHEIDKLIMAATBEHEERSING opgehaald te worden? Indien het laatste het geval is, dient daarvoor #53 geimplementeerd te worden.
Echter zal dat niet in alle gevallen volstaan omdat er EENHEIDKLIMAATBEHEERSING is die zowel individueel als collectief kan zijn. Dit zal dus apart op een eenheid via EENHEIDKLIMAATBEHEERSINGSOORT moeten kunnen worden gespecificeerd.

**Comment by benverhees** [comment]
Ik realiseer mij net dat het ophalen via de parent referentiedata niet volstaat omdat er EENHEIDKLIMAATBEHEERSING is die zowel individueel als collectief kan zijn. Dit zal dus apart op een eenheid moeten kunnen worden gespecificeerd.

**Comment by MarcelVanDenBos** [comment]
Dank voor je suggestie, hebben klimaatbeheersingsoort opgenomen op de eenheid en ruimte klassen.
