### ISSUE TITLE
Uitbreiding CLUSTERSOORT

### ISSUE THREAD

**Issue by renkosteenbeek** [Aedes-datastandaarden/vera-openapi#56]
Een eenheid is vaak deel van een complex. Het is logisch dat dit als 'cluster' gezien wordt met CLUSTERSOORT 'complex'.

Klopt deze interpretatie? Zo ja, kan dan de clustersoort Complex worden toegevoegd in de referentiedata?

**Comment by benataedes** [comment]
Beste Renko,

Een complex en een cluster worden gezien als synoniemen van elkaar. Zie ook [(https://www.coraveraonline.nl/index.php/Id-ac3fdc45-c220-de52-7d39-f50b4e85ffa2)](https://www.coraveraonline.nl/index.php/Id-ac3fdc45-c220-de52-7d39-f50b4e85ffa2). Een complex / cluster is een groepering van eenheden die vanwege een administratieve of andere bedrijfsmatige redenen onderscheiden worden. Een complex zelf is geen reden van onderscheiding, vaak is dit dan een financiële groepering of een onderhoudsgroepering. De clustersoort wordt dan FIN of OND.

Groet,
Ben
VERA-architectuurteam
