### ISSUE TITLE
Maximale lengte, breedte en vrije hoogte toevoegen aan Eenheden-Ruimte

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-openapi#63]
Voor de berekening van de woningwaardering is het nodig de maximale lengte, breedte en vrije hoogte van een ruimte te weten. Op pagina 37 in het beleidsboek staat hierover:

> Voor privé-buitenruimten worden aan de woning punten toegekend indien de privé-buitenruimte een diepte, breedte en vrije hoogte heeft van 1,50 m of meer.

En op pagina 38 staat met betrekking tot puntenaftrek:

> De voorwaarden dat de privé-buitenruimte een diepte, breedte en vrije hoogte van 1,50 m moet hebben, die gelden om met punten gewaardeerd te kunnen worden, zijn niet relevant bij de vraag of aftrekpunten moeten worden toegepast.

We missen bij Eenheden-Ruimte echter de attributen hiervoor. Daarom zou ik willen voorstellen de volgende attributen toe te voegen:

- lengte: de maximale lengte van de ruimte gemeten in meters.
- breedte: de maximale breedte van de ruimte gemeten in meters.
- hoogte: de maximale vrije hoogte van de ruimte gemeten in meters.

**Comment by MarcelVanDenBos** [comment]
Deze hebben we toegevoegd in Patch 5 van VERA 4.1
