### ISSUE TITLE
Versienummer staat niet correct in .yaml

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-openapi#66]
Bedankt voor de nieuwe release met alle changes!

Er zit helaas wel een fout in het versienummer op verschillende plekken in de .yaml files:

https://github.com/search?q=repo:Aedes-datastandaarden/vera-openapi%20.v4.1.5+240628.18&type=code

**Comment by peterjan-aedesdatastandaarden** [comment]
Hoi Ben, klopt wij hadden het releasenummer per ongeluk verkeerd ingevuld in onze pipeline. Het is inmiddels hersteld.

**Comment by peterjan-aedesdatastandaarden** [comment]
Tag verwijderd, versienummers overal gecorrigeerd, nieuwe commit opnieuw getagged met v4.1.5 en vervolgens gereleased
