### ISSUE TITLE
Eenheidvoorwaarden vs EenheidCriteria

### ISSUE THREAD

**Issue by pfheek** [Aedes-datastandaarden/vera-openapi#67]
In 4.0.19 is de Eenheidvoorwaarden obsolete verklaard. Nu mogen we Eenheidcriteria gebruiken. In de Eenheidvoorwaarden kon je bijvoorbeeld aangeven wat het algemene en voor iedereen geldende minimum en maximum inkomen, leeftijd en aantalPersonen was. Hoe doe ik dat met Eenheidcriteria? Welke soort en detailsoort mag ik dan gebruiken?

**Comment by peterjan-aedesdatastandaarden** [comment]
Excuus dat dit issue zo lang is blijven liggen. In de referentiedata EENHEIDCRITERIUMSOORT zijn we deze grootheden vergeten op te nemen. We voegen Inkomen, Leeftijd en Aantal personen toe.
