### ISSUE TITLE
Datum afsluiten huurovereenkomst

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-openapi#69]
In het nieuwe woningwaarderingsstelsel is de datum van het afsluiten van de huurovereenkomst bepalend voor het vaststellen van de waardering van een Rijksmonument. Wij gebruiken hiervoor de BVG modellen, echter zie ik daarin geen relatie tussen een eenheid en de datum van het afsluiten van de huurovereenkomst.

Hoe zouden we dit het beste kunnen specificeren?

Wellicht niet helemaal zuiver, maar in afwachting van een aanpassing van VERA hebben we dit in onze software voor nu met een attribuut `datumAfsluitenHuurovereenkomst` op `EenhedenEenheid` opgelost.

**Comment by EwoutAtAedes** [comment]
Beste Ben, het gaat hier om de datum waarop het contract getekend is (en niet de datum waarop het contract ingaat). In de klasse Overeenkomst is hier nog geen attribuut voor opgenomen. 

Het toevoegen van de tekendatum bij Eenheid is, zoals je zelf ook aangeeft, niet zuiver en moeten we daarom ook niet doen. Daarvoor in de plaats kunnen we een attribuut toevoegen aan Overeenkomst: **ondertekendatum** en toevoegen aan BOG/Overeenkomsten. Is dat voor jullie werkbaar?

**Comment by benverhees** [comment]
Beste Ewout,

Dank je wel voor je reactie. Hoe zou ik, vanuit het BVG/Eenheid model, dat wij gebruiken omdat daarin ook de modellen voor de woningwaardering zich bevinden, een relatie kunnen leggen naar dit toe te voegen attribuut op het Overeenkomst model?

**Comment by EwoutAtAedes** [comment]
Beste Ben, 
enigszins verlate reactie: die informatie kan inderdaad niet in 1 call opgehaald worden en zou je dan met een aanvullende call op Overeenkomst moeten ophalen. Ik begrijp dat dit erg omslachtig is en wellicht ook niet werkbaar maar een attribuut bij Eenheid opnemen is architectuur technisch niet wenselijk. 

Je kunt er uiteraard wel voor kiezen om dit gegeven in het eigen ERP-systeem wel op de eenheid vast te leggen en als extra-attributen mee te geven op BVG/Eenheden.
```
{
    "attributen van de eenheid": "waardes",
    "extra-attributen": [
      {
        "naam": "datumAfsluitenHuurovereenkomst",
        "waarde": "2024-12-12"
      }
}
```
