### ISSUE TITLE
Installaties ontbreekt in BVG model op Eenheden-Ruimte niveau

### ISSUE THREAD

**Issue by sTomerG** [Aedes-datastandaarden/vera-openapi#70]
Op de wiki zie ik `installaties` toegevoegd aan `Eenheden-Ruimte`: https://www.coraveraonline.nl/index.php/Klasse:BVG-Eenheden-Ruimte/VERA_4.1_Patches

Echter, ik zie `installaties` niet als property van `Eenheden-Ruimte` in _ketenprocessen/bvg.yaml_.

Zou deze toegevoegd kunnen worden?

**Comment by MarcelVanDenBos** [comment]
Opgelost in VERA 4.1.6
