### ISSUE TITLE
Uitbreiding zoekmogelijkheden

### ISSUE THREAD

**Issue by renkosteenbeek** [Aedes-datastandaarden/vera-openapi#72]
**Huidige situatie**
De Vera API standaard ondersteunt momenteel alleen de zoekoperator "IS GELIJK AAN" voor het uitvoeren van zoekopdrachten.

**Gewenste functionaliteit**
We stellen voor om de zoekfunctionaliteit van de Vera API uit te breiden met aanvullende zoekoperatoren. Dit zal de flexibiliteit en bruikbaarheid van de API aanzienlijk verbeteren.
Voorgestelde nieuwe zoekoperatoren:

- BEVAT
- BEGINT MET
- EINDIGT MET
- GROTER DAN
- KLEINER DAN
- TUSSEN
- IS NIET GELIJK AAN

**Voordelen**
Door specifieker te kunnen zoeken is het mogelijk om veel snellere API calls uit te voeren. Voorbeeld:
Als ik van een huurder de facturen van de laatste 2 jaar wil hebben, dan kan ik nu alleen maar alle facturen ophalen (+paginering) en achteraf filteren. Alle pagina's uitlezen zal nu moeten, gezien Vera geen sortingsmogelijkheden heeft.

**Comment by EwoutAtAedes** [comment]
Hi Renko,

het uitbreiden van de zoekfilters is binnen het VERA team ook een wens alleen kan dit grote gevolgen hebben voor de leveranciers. Deze wens staat in ieder geval op onze backlog. Noot: voor de implementatie hiervan zullen wel zoveel mogelijk uitgaan van de notatie-conventies van OData.
