### ISSUE TITLE
Typo in omschrijving ruimte op bouwkundigelement

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-openapi#74]
In de omschrijving voor het attribuut ruimte op bouwkundigelement staat `waain` ipv `waarin`:

https://github.com/search?q=repo:Aedes-datastandaarden/vera-openapi%20waain&type=code

**Comment by EwoutAtAedes** [comment]
De tekst hebben we aangepast en komt mee in de volgende patch-versie
