### ISSUE TITLE
Er wordt nog verwezen naar referentiedatasoort `Installatiesoort`, terwijl dit in de referentiedata `Voorzieningsoort` is geworden

### ISSUE THREAD

**Issue by benverhees** [Aedes-datastandaarden/vera-openapi#75]
https://github.com/search?q=repo:Aedes-datastandaarden/vera-openapi+INSTALLATIESOORT&type=code

**Comment by EwoutAtAedes** [comment]
Hoi Ben, de obsolete verklaring is teruggedraaid. Blijkbaar waren de wijzigingen in de attributen niet meegekomen in de laatste patch.

**Comment by benverhees** [comment]
@EwoutAtAedes zou dit dan niet juist in deze repository aangepast moeten worden?

**Comment by EwoutvdWielen** [comment]
@benverhees, missend domein toegevoegd. Het aanpassen van de OpenAPI specificaties doen we 1x per kwartaal, de referentiedata kunnen we ieder ogenblik updaten. Ivm consistentie is ervoor gekozen om de referentiedata aan te passen.
