### ISSUE TITLE
Vera ketenprocessen: Correcte implementatie voor betalingsregelingen en iDeal-betalingen

### ISSUE THREAD

**Issue by renkosteenbeek** [Aedes-datastandaarden/vera-openapi#79]
## Context
Ik ontwikkel een applicatie die integreert met de Vera ketenprocessen API's. Specifiek wil ik de volgende functionaliteiten implementeren:

## Processtappen
1. Het ophalen van bestaande betalingsregelingen (via Vera, "betalingsregelingen")
2. Het verwerken van iDeal-betalingen voor individuele termijnen door huurders (buiten Vera)
3. Het terugmelden van succesvolle betalingen aan Vera voor verwerking in het ERP-systeem (via Vera)

## Vraag
Wat is de aanpak volgens de Vera-specificaties voor deze implementatie? Graag specifiek advies over de terugkoppeling naar het ERP systeem.

**Comment by EwoutAtAedes** [comment]
Hoi Renko,
het proces rondom het betalen van openstaande boekingen en het resultaat hiervan weer terug krijgen uit het achterliggende financiële systeem is inderdaad wat complexer omdat er gekoppeld wordt met een 'derde' partij (de bank, via iDeal). Stap 3 in jouw proces is als scenario niet beschreven op de WIKI. Er is echter wel een geschikte resource voor: PATCH BFG/Boekingen. Uit ons gesprek van zojuist blijkt dat dit ook al toegepast wordt bij één ERP-leverancier. 

We hebben op onze backlog een taak aangemaakt om dit scenario te beschrijven op de WIKI.
